export const navLinks = [
  { name: "Home", link: "/" },
  { name: "Gallery", link: "/gallery" },
  { name: "Buy Print", link: "buyprint" },
];

export const imagesData = [
  { src: "/night1.jpg", alt: "night1" },
  { src: "/night2.jpg", alt: "night2" },
  { src: "/night3.jpg", alt: "night3" },
  { src: "/night4.jpg", alt: "night4" },
  { src: "/night5.jpg", alt: "night5" },
  { src: "/structure1.jpg", alt: "structure1" },
  { src: "/structure2.jpg", alt: "structure2" },
  { src: "/structure3.jpg", alt: "structure3" },
  { src: "/structure4.jpg", alt: "structure4" },
  { src: "/structure5.jpg", alt: "structure5" },
  { src: "/people1.jpg", alt: "people1" },
  { src: "/people2.jpg", alt: "people2" },
  { src: "/people3.jpg", alt: "people3" },
  { src: "/people4.jpg", alt: "people4" },
  { src: "/people5.jpg", alt: "people5" },
  { src: "/nature1.jpg", alt: "nature1" },
  { src: "/nature2.jpg", alt: "nature2" },
  { src: "/nature3.jpg", alt: "nature3" },
  { src: "/nature4.jpg", alt: "nature4" },
  { src: "/nature5.jpg", alt: "nature5" },
  { src: "/black1.jpg", alt: "black1" },
  { src: "/black2.jpg", alt: "black2" },
  { src: "/black3.jpg", alt: "black3" },
  { src: "/black4.jpg", alt: "black4" },
  { src: "/black5.jpg", alt: "black5" },
];
